# Use an official Node.js runtime as the base image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install
RUN npm install pm2 -g
# Copy the rest of the application code to the working directory
COPY . .

# Expose the port the app runs on
#EXPOSE 4030

# Command to run the application
#CMD ["node", "app.js"]
CMD ["pm2-runtime", "server.js"]
